In [3]:
import pandas as pd

try:
    pd.read_html('https://www.hockey-reference.com/leagues/NHL_2020_skaters.html')
except Exception as e:
    print(e)

<urlopen error [Errno -3] Temporary failure in name resolution>

In [10]:
df = pd.read_csv('orig_csvs/Player_Stats_Reg3.csv')
df

,Player,Age,Tm,Pos,GP,G,A,PTS,+/-,PIM,...,S%,TOI,BLK,HIT,FOW,FOL,FO%,pid,Year,YR_INT
0,Justin Abdelkader,32,DET,LW,49,0,3,3,-14.0,25.0,...,0.0,565.0,26.0,103.0,38.0,31.0,55.1,abdelju01,2019-2020,2020
1,Pontus Aberg,26,TOR,LW,5,0,1,1,0.0,0.0,...,0.0,44.0,1.0,1.0,0.0,0.0,NaN,abergpo01,2019-2020,2020
2,Vitaly Abramov,21,OTT,RW,2,1,0,1,0.0,2.0,...,33.3,12.0,0.0,0.0,0.0,0.0,NaN,abramvi01,2019-2020,2020
3,Noel Acciari,28,FLA,C,66,20,7,27,2.0,21.0,...,18.5,1054.0,103.0,121.0,381.0,414.0,47.9,acciano01,2019-2020,2020
4,Andrew Agozzino,29,PIT,LW,17,0,2,2,0.0,4.0,...,0.0,112.0,5.0,19.0,30.0,29.0,50.8,agozzan01,2019-2020,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45785,Hamby Shore,31,OTS,LW,18,3,8,11,NaN,51.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,shoreha01,1917-1918,1918
45786,Raymie Skilton,28,MTW,C,1,0,0,0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,skiltra01,1917-1918,1918
45787,Alf Skinner,22,TRA,RW,20,13,5,18,NaN,34.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,skinnal01,1917-1918,1918
45788,Phil Stevens,24,MTW,D,4,1,0,1,NaN,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,steveph01,1917-1918,1918
45789,Ken Thompson,36,MTW,F,1,0,0,0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,thompke01,1917-1918,1918

In [7]:
df = df.drop(columns = ['Rk'])
df

,Player,Age,Tm,Pos,GP,G,A,PTS,+/-,PIM,...,S%,TOI,BLK,HIT,FOW,FOL,FO%,pid,Year,YR_INT
0,Justin Abdelkader,32,DET,LW,49,0,3,3,-14.0,25.0,...,0.0,565.0,26.0,103.0,38.0,31.0,55.1,abdelju01,2019-2020,2020
1,Pontus Aberg,26,TOR,LW,5,0,1,1,0.0,0.0,...,0.0,44.0,1.0,1.0,0.0,0.0,NaN,abergpo01,2019-2020,2020
2,Vitaly Abramov,21,OTT,RW,2,1,0,1,0.0,2.0,...,33.3,12.0,0.0,0.0,0.0,0.0,NaN,abramvi01,2019-2020,2020
3,Noel Acciari,28,FLA,C,66,20,7,27,2.0,21.0,...,18.5,1054.0,103.0,121.0,381.0,414.0,47.9,acciano01,2019-2020,2020
4,Andrew Agozzino,29,PIT,LW,17,0,2,2,0.0,4.0,...,0.0,112.0,5.0,19.0,30.0,29.0,50.8,agozzan01,2019-2020,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45785,Hamby Shore,31,OTS,LW,18,3,8,11,NaN,51.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,shoreha01,1917-1918,1918
45786,Raymie Skilton,28,MTW,C,1,0,0,0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,skiltra01,1917-1918,1918
45787,Alf Skinner,22,TRA,RW,20,13,5,18,NaN,34.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,skinnal01,1917-1918,1918
45788,Phil Stevens,24,MTW,D,4,1,0,1,NaN,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,steveph01,1917-1918,1918
45789,Ken Thompson,36,MTW,F,1,0,0,0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,thompke01,1917-1918,1918

In [9]:
df.to_csv('orig_csvs/Player_Stats_Reg3.csv', index = False)