In [184]:
import requests
from bs4 import BeautifulSoup
import re
import pandas as pd
import numpy as np
import string
import time
import datetime

# Scraping

In [2]:
letters = string.ascii_lowercase.replace('x', '')
letters

'abcdefghijklmnopqrstuvwyz'

In [25]:
pid = []
names = []
infos = []

for l in letters:

    all_url = f'https://www.hockey-reference.com/players/{l}/'
    print(all_url)
    resp = requests.get(all_url)
    soup = BeautifulSoup(resp.text, 'html.parser')
    slinks = soup.select("#div_players a")
    surl = ['https://www.hockey-reference.com'+s['href'] for s in slinks]
    
    for i in range(len(surl)):
        if i % 37 == 0:
            time.sleep(13)
        else:
            time.sleep(1)
        resp2= requests.get(surl[i])
        soup2 = BeautifulSoup(resp2.text, 'html.parser')
        slinks2 = soup2.select("#meta p")


        pl_id = slinks[i].attrs['href'].split('/')[3].split('.')[0]
        pl_nm = soup2.select('span')[8].text
        pl_inf = [slinks2[y].text for y in range(len(slinks2))]

        pid.append(pl_id)
        names.append(pl_nm)
        infos.append(pl_inf)

https://www.hockey-reference.com/players/a/
https://www.hockey-reference.com/players/b/
https://www.hockey-reference.com/players/c/
https://www.hockey-reference.com/players/d/
https://www.hockey-reference.com/players/e/
https://www.hockey-reference.com/players/f/
https://www.hockey-reference.com/players/g/
https://www.hockey-reference.com/players/h/
https://www.hockey-reference.com/players/i/
https://www.hockey-reference.com/players/j/
https://www.hockey-reference.com/players/k/
https://www.hockey-reference.com/players/l/
https://www.hockey-reference.com/players/m/
https://www.hockey-reference.com/players/n/
https://www.hockey-reference.com/players/o/
https://www.hockey-reference.com/players/p/
https://www.hockey-reference.com/players/q/
https://www.hockey-reference.com/players/r/
https://www.hockey-reference.com/players/s/
https://www.hockey-reference.com/players/t/
https://www.hockey-reference.com/players/u/
https://www.hockey-reference.com/players/v/
https://www.hockey-reference.com/players/w/
https://www.hockey-reference.com/players/y/
https://www.hockey-reference.com/players/z/

## Single Letter

In [7]:
l = 'u'
all_url = f'https://www.hockey-reference.com/players/{l}/'
print(all_url)
resp = requests.get(all_url)
soup = BeautifulSoup(resp.text, 'html.parser')
slinks = soup.select("#div_players a")
surl = ['https://www.hockey-reference.com'+s['href'] for s in slinks]

surl

pid = []
names = []
infos = []

for i in range(len(surl)):
    if i % 37 == 0:
        time.sleep(13)
    else:
        time.sleep(1)
    resp2= requests.get(surl[i])
    soup2 = BeautifulSoup(resp2.text, 'html.parser')
    slinks2 = soup2.select("#meta p")


    pl_id = slinks[i].attrs['href'].split('/')[3].split('.')[0]
    pl_nm = soup2.select('span')[8].text
    pl_inf = [slinks2[y].text for y in range(len(slinks2))]
    
    pid.append(pl_id)
    names.append(pl_nm)
    infos.append(pl_inf)

https://www.hockey-reference.com/players/u/

In [26]:
df = pd.DataFrame(list(zip(pid,names,infos)), columns = ['pid', 'Player', 'info'])
df

,pid,Player,info
0,aaltoan01,Antti Aalto,"[Position: C • Shoots: Left\n, 6-1, 210lb ..."
1,aaltoju01,Juhamatti Aaltonen,"[Position: RW\n, Born: June 4, 1985 , Draf..."
2,aaltole01,Leevi Aaltonen,"[Position: RW • Shoots: Left\n, 5-8, 177lb..."
3,aaltomi01,Miro Aaltonen,"[Position: C • Shoots: Left\n, 6-0, 176lb ..."
4,abbeybr01,Bruce Abbey,"[Position: D • Shoots: Left\n, 6-1, 185lb ..."
...,...,...,...
11360,zukwa01,Wayne Zuk,"[Position: C • Shoots: Right\n, 5-8, 160lb..."
11361,zukemi01,Mike Zuke,"[Position: C • Shoots: Right\n, 6-0, 180lb..."
11362,zunicru01,Rudy Zunich,"[Position: D • Shoots: Left\n, 5-9, 170lb ..."
11363,zykovva01,Valentin Zykov,"[Position: LW • Shoots: Right\n, 6-0, 200l..."
11364,zyuzian01,Andrei Zyuzin,"[Position: D • Shoots: Left\n, 6-1, 208lb ..."

In [156]:
df1 = pd.read_csv('Player_List_Raw.csv')
df1

,pid,Player,info
0,aaltoan01,Antti Aalto,"['Position: C\xa0•\xa0 Shoots: Left\n', '6-..."
1,aaltoju01,Juhamatti Aaltonen,"['Position: RW\n', ' Born: June 4,\xa01985 ..."
2,aaltole01,Leevi Aaltonen,"['Position: RW\xa0•\xa0 Shoots: Left\n', '5..."
3,aaltomi01,Miro Aaltonen,"['Position: C\xa0•\xa0 Shoots: Left\n', '6-..."
4,abbeybr01,Bruce Abbey,"['Position: D\xa0•\xa0 Shoots: Left\n', '6-..."
...,...,...,...
11360,zukwa01,Wayne Zuk,"['Position: C\xa0•\xa0 Shoots: Right\n', '5..."
11361,zukemi01,Mike Zuke,"['Position: C\xa0•\xa0 Shoots: Right\n', '6..."
11362,zunicru01,Rudy Zunich,"['Position: D\xa0•\xa0 Shoots: Left\n', '5-..."
11363,zykovva01,Valentin Zykov,"['Position: LW\xa0•\xa0 Shoots: Right\n', '..."
11364,zyuzian01,Andrei Zyuzin,"['Position: D\xa0•\xa0 Shoots: Left\n', '6-..."

# Transform

## All Transform

In [407]:
poss = []
bds = []
shoots_list = []
height_list_imp = []
height_list_met = []
weights = []
cities = []
states = []
countries = []

for i in range(len(df1['info'])):
    strang = df1['info'][i]
    
    # Position
    if 'Position: ' in strang:
        mo = re.search('Position: \w*([/]\w*)?', strang)
        mo_str = mo.group().split('Position: ')[1]
        poss.append(mo_str)
    else:
        poss.append('')

    # Date of Birth    
    if re.search(r'Born:  \w* \d{1,2},\\xa\d*', strang):
        mo = re.search(r'Born:  \w* \d{1,2},\\xa\d*', strang)
        mo_str = mo.group()
        byr = mo_str[-4:]
        bd = mo_str.split('Born:  ')[1].split(',')[0]
        b_str = bd + ' ' + byr
        b_dt = datetime.datetime.strptime(b_str, '%B %d %Y')
        b_strf = datetime.datetime.strftime(b_dt, '%Y-%m-%d')  #getting proper sql date formatting
        bds.append(b_strf)
    else:
        bds.append('')
        
    # Shoots
    if 'Shoots: ' in strang:
        mo = re.search(r'Shoots: \w*', strang)
        mo_str = mo.group()
        shoots = mo_str.split('Shoots: ')[1]
        shoots_list.append(shoots)
    else:
        shoots_list.append('')
        
    # Height    
    if re.search('\d-\d{1,2}', strang):
        mo = re.search('\d-\d{1,2}', strang)
        mo_str = mo.group()
        height_list_imp.append(mo_str)
    else:
        height_list_imp.append('')
        
    if re.search('\d*cm', strang):
        mo = re.search('\d*cm', strang)
        mo_str = mo.group() 
        height_cm = mo_str.split('cm')[0]
        height_list_met.append(height_cm)
    else:
        height_list_met.append('')
        
    # Weight
    if re.search('\d*lb', strang):
        mo = re.search('\d*lb', strang)
        mo_str = mo.group()
        wt = mo_str.split('lb')[0][1:]
        weights.append(wt)
    else:
        weights.append('')
        
    # Birthplace
    if re.search(r'in\\xa0\w*,\\xa0\w*  \w*', strang):
        mo = re.search(r'in\\xa0\w*,\\xa0\w*  \w*', strang)
        mo_str = mo.group()
        city = mo_str.split('in\\xa0')[1].split(',')[0]
        state = mo_str.split('in\\xa0')[1].split(',\\xa0')[1].split(' ')[0]
        country = mo_str.split('in\\xa0')[1].split(',\\xa0')[1].split('  ')[1]
        cities.append(city)
        states.append(state)
        countries.append(country)
    else:
        cities.append('')
        states.append('')
        countries.append('')

df1['Position'] = poss
df1['dob'] = bds
df1['Shoots'] = shoots_list
df1['height'] = height_list_imp
df1['height_cm'] = height_list_met
df1['weight']  = weights
df1['city'] = cities
df1['state'] = states
df1['country'] = countries

In [408]:
df1

,pid,Player,info,Position,dob,Shoots,height,height_cm,weight,city,state,country
0,aaltoan01,Antti Aalto,"['Position: C\xa0•\xa0 Shoots: Left\n', '6-...",C,1975-03-04,Left,6-1,185,210,Lappeenranta,Finland,fi
1,aaltoju01,Juhamatti Aaltonen,"['Position: RW\n', ' Born: June 4,\xa01985 ...",RW,1985-06-04,,,,,,,
2,aaltole01,Leevi Aaltonen,"['Position: RW\xa0•\xa0 Shoots: Left\n', '5...",RW,2001-01-24,Left,5-8,173,177,Mikkeli,Finland,fi
3,aaltomi01,Miro Aaltonen,"['Position: C\xa0•\xa0 Shoots: Left\n', '6-...",C,1993-06-07,Left,6-0,183,176,Joensuu,Finland,fi
4,abbeybr01,Bruce Abbey,"['Position: D\xa0•\xa0 Shoots: Left\n', '6-...",D,1951-08-18,Left,6-1,185,185,Toronto,Ontario,ca
...,...,...,...,...,...,...,...,...,...,...,...,...
11360,zukwa01,Wayne Zuk,"['Position: C\xa0•\xa0 Shoots: Right\n', '5...",C,1949-10-29,Right,5-8,173,160,,,
11361,zukemi01,Mike Zuke,"['Position: C\xa0•\xa0 Shoots: Right\n', '6...",C,1954-04-16,Right,6-0,183,180,,,
11362,zunicru01,Rudy Zunich,"['Position: D\xa0•\xa0 Shoots: Left\n', '5-...",D,1910-11-24,Left,5-9,175,170,Calumet,Michigan,us
11363,zykovva01,Valentin Zykov,"['Position: LW\xa0•\xa0 Shoots: Right\n', '...",LW,1995-05-15,Right,6-0,183,200,,,
11364,zyuzian01,Andrei Zyuzin,"['Position: D\xa0•\xa0 Shoots: Left\n', '6-...",D,1978-01-21,Left,6-1,185,208,Ufa,USSR,su

In [415]:
df1.drop('info', axis = 1).to_csv('Player_List.csv', index = False)

## Position

In [169]:
poss = []
for i in range(len(df1['info'])):
    strang = df1['info'][i]
    if 'Position: ' in strang:
        #mo = re.search('Position: \w*[/]?\w*[/]?\w*[/]?\w*', strang) # can accept up to 4 different positions
        mo = re.search('Position: \w*([/]\w*)?', strang)
        mo_str = mo.group().split('Position: ')[1]
        poss.append(mo_str)
    else:
        poss.append('')

In [171]:
df1['Position'] = poss
df1

,pid,Player,info,Position
0,aaltoan01,Antti Aalto,"['Position: C\xa0•\xa0 Shoots: Left\n', '6-...",C
1,aaltoju01,Juhamatti Aaltonen,"['Position: RW\n', ' Born: June 4,\xa01985 ...",RW
2,aaltole01,Leevi Aaltonen,"['Position: RW\xa0•\xa0 Shoots: Left\n', '5...",RW
3,aaltomi01,Miro Aaltonen,"['Position: C\xa0•\xa0 Shoots: Left\n', '6-...",C
4,abbeybr01,Bruce Abbey,"['Position: D\xa0•\xa0 Shoots: Left\n', '6-...",D
...,...,...,...,...
11360,zukwa01,Wayne Zuk,"['Position: C\xa0•\xa0 Shoots: Right\n', '5...",C
11361,zukemi01,Mike Zuke,"['Position: C\xa0•\xa0 Shoots: Right\n', '6...",C
11362,zunicru01,Rudy Zunich,"['Position: D\xa0•\xa0 Shoots: Left\n', '5-...",D
11363,zykovva01,Valentin Zykov,"['Position: LW\xa0•\xa0 Shoots: Right\n', '...",LW
11364,zyuzian01,Andrei Zyuzin,"['Position: D\xa0•\xa0 Shoots: Left\n', '6-...",D

In [241]:
df1['Position'].value_counts()

D       3404
C       2398
LW      1964
RW      1873
G       1173
C/LW      96
F         91
C/RW      74
W         49
LW/C      46
          44
LW/D      30
RW/D      26
RW/C      24
D/LW      18
C/D       14
D/RW      14
R          8
P          6
D/C        5
C/W        4
D/W        2
R/C        1
F/D        1
Name: Position, dtype: int64

In [173]:
df1[df1['Position'] == 'P']

,pid,Player,info,Position
956,boondi01,Dickie Boon,"['Position: P\n', '5-5,\xa0130lb\xa0(165cm,\xa...",P
3426,gibsoja01,Jack Gibson,"['Position: P\n', '6-0,\xa0185lb\xa0(183cm,\xa...",P
3643,grantmi01,Mike Grant,"['Position: P\n', ' Born: November 27,\xa0187...",P
3717,griffsi01,Si Griffis,"['Position: P\xa0•\xa0 Shoots: Left\n', '6-...",P
8385,pulfoha01,Harvey Pulford,"['Position: P\n', ' Born: April 22,\xa01875 ...",P
10004,stuarho01,Hod Stuart,"['Position: P\n', '6-0,\xa0190lb\xa0(183cm,\xa...",P

## Birthdates

In [294]:
bds = []
for i in range(len(df1['info'])):
    strang = df1['info'][i]
    if 'Born: ' in strang:
        try:
            mo = re.search(r'Born:  \w* \d{1,2},\\xa\d*', strang)
            mo_str = mo.group()
            byr = mo_str[-4:]
            bd = mo_str.split('Born:  ')[1].split(',')[0]

            b_str = bd + ' ' + byr
            b_dt = datetime.datetime.strptime(b_str, '%B %d %Y')
            b_strf = datetime.datetime.strftime(b_dt, '%Y-%m-%d')  #getting proper sql date formatting
            bds.append(b_strf)
        except AttributeError:                                     # attribute error for few rows with only birth year info
            bds.append('')
    else:
        bds.append('')

In [295]:
df1['dob'] = bds
df1

,pid,Player,info,Position,dob
0,aaltoan01,Antti Aalto,"['Position: C\xa0•\xa0 Shoots: Left\n', '6-...",C,1975-03-04
1,aaltoju01,Juhamatti Aaltonen,"['Position: RW\n', ' Born: June 4,\xa01985 ...",RW,1985-06-04
2,aaltole01,Leevi Aaltonen,"['Position: RW\xa0•\xa0 Shoots: Left\n', '5...",RW,2001-01-24
3,aaltomi01,Miro Aaltonen,"['Position: C\xa0•\xa0 Shoots: Left\n', '6-...",C,1993-06-07
4,abbeybr01,Bruce Abbey,"['Position: D\xa0•\xa0 Shoots: Left\n', '6-...",D,1951-08-18
...,...,...,...,...,...
11360,zukwa01,Wayne Zuk,"['Position: C\xa0•\xa0 Shoots: Right\n', '5...",C,1949-10-29
11361,zukemi01,Mike Zuke,"['Position: C\xa0•\xa0 Shoots: Right\n', '6...",C,1954-04-16
11362,zunicru01,Rudy Zunich,"['Position: D\xa0•\xa0 Shoots: Left\n', '5-...",D,1910-11-24
11363,zykovva01,Valentin Zykov,"['Position: LW\xa0•\xa0 Shoots: Right\n', '...",LW,1995-05-15
11364,zyuzian01,Andrei Zyuzin,"['Position: D\xa0•\xa0 Shoots: Left\n', '6-...",D,1978-01-21

In [296]:
df1['dob'].value_counts()

              85
1984-06-05     5
1994-01-14     5
1999-06-01     5
1982-01-15     5
              ..
1983-04-30     1
1965-11-18     1
1982-04-19     1
2002-04-05     1
1993-07-31     1
Name: dob, Length: 8990, dtype: int64

## Shoots

In [305]:
strang = df1['info'][0]
strang

"['Position: C\\xa0•\\xa0    Shoots: Left\\n', '6-1,\\xa0210lb\\xa0(185cm,\\xa095kg) ', ' Born:  March 4,\\xa01975   in\\xa0Lappeenranta,\\xa0Finland  fi ', 'Draft: Anaheim, 6th round (134th\\xa0overall), 1993\\xa0NHL\\xa0Entry ']"

In [304]:
mo = re.search(r'Shoots: \w*', strang)
mo_str = mo.group()
shoots = mo_str.split('Shoots: ')[1]
shoots

'Left'

In [306]:
shoots_list = []
for i in range(len(df1['info'])):
    strang = df1['info'][i]
    if 'Shoots: ' in strang:
        mo = re.search(r'Shoots: \w*', strang)
        mo_str = mo.group()
        shoots = mo_str.split('Shoots: ')[1]
        shoots_list.append(shoots)
    else:
        shoots_list.append('')

In [308]:
df1['Shoots'] = shoots_list
df1

,pid,Player,info,Position,dob,Shoots
0,aaltoan01,Antti Aalto,"['Position: C\xa0•\xa0 Shoots: Left\n', '6-...",C,1975-03-04,Left
1,aaltoju01,Juhamatti Aaltonen,"['Position: RW\n', ' Born: June 4,\xa01985 ...",RW,1985-06-04,
2,aaltole01,Leevi Aaltonen,"['Position: RW\xa0•\xa0 Shoots: Left\n', '5...",RW,2001-01-24,Left
3,aaltomi01,Miro Aaltonen,"['Position: C\xa0•\xa0 Shoots: Left\n', '6-...",C,1993-06-07,Left
4,abbeybr01,Bruce Abbey,"['Position: D\xa0•\xa0 Shoots: Left\n', '6-...",D,1951-08-18,Left
...,...,...,...,...,...,...
11360,zukwa01,Wayne Zuk,"['Position: C\xa0•\xa0 Shoots: Right\n', '5...",C,1949-10-29,Right
11361,zukemi01,Mike Zuke,"['Position: C\xa0•\xa0 Shoots: Right\n', '6...",C,1954-04-16,Right
11362,zunicru01,Rudy Zunich,"['Position: D\xa0•\xa0 Shoots: Left\n', '5-...",D,1910-11-24,Left
11363,zykovva01,Valentin Zykov,"['Position: LW\xa0•\xa0 Shoots: Right\n', '...",LW,1995-05-15,Right
11364,zyuzian01,Andrei Zyuzin,"['Position: D\xa0•\xa0 Shoots: Left\n', '6-...",D,1978-01-21,Left

In [310]:
df1['Shoots'].value_counts()

Left     5555
Right    3207
         2603
Name: Shoots, dtype: int64

## Heights

In [319]:
strang = df1['info'][0]
strang

"['Position: C\\xa0•\\xa0    Shoots: Left\\n', '6-1,\\xa0210lb\\xa0(185cm,\\xa095kg) ', ' Born:  March 4,\\xa01975   in\\xa0Lappeenranta,\\xa0Finland  fi ', 'Draft: Anaheim, 6th round (134th\\xa0overall), 1993\\xa0NHL\\xa0Entry ']"

In [335]:
mo = re.search('\d-\d', strang)
mo_str = mo.group()

mo_str

'6-1'

In [340]:
mo = re.search('\d*cm', strang)
mo_str = mo.group()

mo_str.split('cm')[0]

'185'

In [359]:
height_list_imp = []
height_list_met = []
for i in range(len(df1['info'])):
    strang = df1['info'][i]
    if re.search('\d-\d{1,2}', strang):
        mo = re.search('\d-\d{1,2}', strang)
        mo_str = mo.group()
        height_list_imp.append(mo_str)
    else:
        height_list_imp.append('')
        
    if re.search('\d*cm', strang):
        mo = re.search('\d*cm', strang)
        mo_str = mo.group() 
        height_cm = mo_str.split('cm')[0]
        height_list_met.append(height_cm)
    else:
        height_list_met.append('')
mo_str

'185cm'

In [360]:
df1['height'] = height_list_imp
df1['height_cm'] = height_list_met
df1

,pid,Player,info,Position,dob,Shoots,height,height_cm
0,aaltoan01,Antti Aalto,"['Position: C\xa0•\xa0 Shoots: Left\n', '6-...",C,1975-03-04,Left,6-1,185
1,aaltoju01,Juhamatti Aaltonen,"['Position: RW\n', ' Born: June 4,\xa01985 ...",RW,1985-06-04,,,
2,aaltole01,Leevi Aaltonen,"['Position: RW\xa0•\xa0 Shoots: Left\n', '5...",RW,2001-01-24,Left,5-8,173
3,aaltomi01,Miro Aaltonen,"['Position: C\xa0•\xa0 Shoots: Left\n', '6-...",C,1993-06-07,Left,6-0,183
4,abbeybr01,Bruce Abbey,"['Position: D\xa0•\xa0 Shoots: Left\n', '6-...",D,1951-08-18,Left,6-1,185
...,...,...,...,...,...,...,...,...
11360,zukwa01,Wayne Zuk,"['Position: C\xa0•\xa0 Shoots: Right\n', '5...",C,1949-10-29,Right,5-8,173
11361,zukemi01,Mike Zuke,"['Position: C\xa0•\xa0 Shoots: Right\n', '6...",C,1954-04-16,Right,6-0,183
11362,zunicru01,Rudy Zunich,"['Position: D\xa0•\xa0 Shoots: Left\n', '5-...",D,1910-11-24,Left,5-9,175
11363,zykovva01,Valentin Zykov,"['Position: LW\xa0•\xa0 Shoots: Right\n', '...",LW,1995-05-15,Right,6-0,183
11364,zyuzian01,Andrei Zyuzin,"['Position: D\xa0•\xa0 Shoots: Left\n', '6-...",D,1978-01-21,Left,6-1,185

In [361]:
df1['height'].value_counts()

6-0     1623
6-1     1609
        1525
5-11    1484
6-2     1310
5-10    1049
6-3      860
5-9      563
6-4      450
5-8      348
6-5      180
5-7      138
6-6       93
5-6       73
6-7       28
5-5       17
6-8       11
5-4        2
5-3        1
6-9        1
Name: height, dtype: int64

In [364]:
df1[df1['height'] == '5-4']

,pid,Player,info,Position,dob,Shoots,height,height_cm
2426,dionco01,Connie Dion,"['Position: G\xa0•\xa0 Catches: Right\n', '...",G,1918-08-11,,5-4,163
3402,gerbena01,Nathan Gerbe,"['Position: C\xa0•\xa0 Shoots: Left\n', '5-...",C,1987-07-24,Left,5-4,163

## Weights

In [351]:
strang = df1['info'][0]
strang

"['Position: C\\xa0•\\xa0    Shoots: Left\\n', '6-1,\\xa0210lb\\xa0(185cm,\\xa095kg) ', ' Born:  March 4,\\xa01975   in\\xa0Lappeenranta,\\xa0Finland  fi ', 'Draft: Anaheim, 6th round (134th\\xa0overall), 1993\\xa0NHL\\xa0Entry ']"

In [353]:
mo = re.search('\d*lb', strang)
mo_str = mo.group()
wt = mo_str.split('lb')[0][1:]
wt

'210'

In [356]:
weights = []
for i in range(len(df1['info'])):
    strang = df1['info'][i]
    if re.search('\d*lb', strang):
        mo = re.search('\d*lb', strang)
        mo_str = mo.group()
        wt = mo_str.split('lb')[0][1:]
        weights.append(wt)
    else:
        weights.append('')

In [365]:
df1['weight']  = weights
df1

,pid,Player,info,Position,dob,Shoots,height,height_cm,weight
0,aaltoan01,Antti Aalto,"['Position: C\xa0•\xa0 Shoots: Left\n', '6-...",C,1975-03-04,Left,6-1,185,210
1,aaltoju01,Juhamatti Aaltonen,"['Position: RW\n', ' Born: June 4,\xa01985 ...",RW,1985-06-04,,,,
2,aaltole01,Leevi Aaltonen,"['Position: RW\xa0•\xa0 Shoots: Left\n', '5...",RW,2001-01-24,Left,5-8,173,177
3,aaltomi01,Miro Aaltonen,"['Position: C\xa0•\xa0 Shoots: Left\n', '6-...",C,1993-06-07,Left,6-0,183,176
4,abbeybr01,Bruce Abbey,"['Position: D\xa0•\xa0 Shoots: Left\n', '6-...",D,1951-08-18,Left,6-1,185,185
...,...,...,...,...,...,...,...,...,...
11360,zukwa01,Wayne Zuk,"['Position: C\xa0•\xa0 Shoots: Right\n', '5...",C,1949-10-29,Right,5-8,173,160
11361,zukemi01,Mike Zuke,"['Position: C\xa0•\xa0 Shoots: Right\n', '6...",C,1954-04-16,Right,6-0,183,180
11362,zunicru01,Rudy Zunich,"['Position: D\xa0•\xa0 Shoots: Left\n', '5-...",D,1910-11-24,Left,5-9,175,170
11363,zykovva01,Valentin Zykov,"['Position: LW\xa0•\xa0 Shoots: Right\n', '...",LW,1995-05-15,Right,6-0,183,200
11364,zyuzian01,Andrei Zyuzin,"['Position: D\xa0•\xa0 Shoots: Left\n', '6-...",D,1978-01-21,Left,6-1,185,208

In [385]:
strang = df1['info'][0]
strang

"['Position: C\\xa0•\\xa0    Shoots: Left\\n', '6-1,\\xa0210lb\\xa0(185cm,\\xa095kg) ', ' Born:  March 4,\\xa01975   in\\xa0Lappeenranta,\\xa0Finland  fi ', 'Draft: Anaheim, 6th round (134th\\xa0overall), 1993\\xa0NHL\\xa0Entry ']"

In [386]:
mo = re.search(r'in\\xa0\w*,\\xa0\w*  \w*', strang)
mo_str = mo.group()
city = mo_str.split('in\\xa0')[1].split(',')[0]
state = mo_str.split('in\\xa0')[1].split(',\\xa0')[1].split(' ')[0]
country = mo_str.split('in\\xa0')[1].split(',\\xa0')[1].split('  ')[1]
country

'fi'

In [388]:
cities = []
states = []
countries = []
for i in range(len(df1['info'])):
    strang = df1['info'][i]
    if re.search(r'in\\xa0\w*,\\xa0\w*  \w*', strang):
        mo = re.search(r'in\\xa0\w*,\\xa0\w*  \w*', strang)
        mo_str = mo.group()
        city = mo_str.split('in\\xa0')[1].split(',')[0]
        state = mo_str.split('in\\xa0')[1].split(',\\xa0')[1].split(' ')[0]
        country = mo_str.split('in\\xa0')[1].split(',\\xa0')[1].split('  ')[1]
        cities.append(city)
        states.append(state)
        countries.append(country)
    else:
        cities.append('')
        states.append('')
        countries.append('')

In [393]:
df1['city'] = cities
df1['state'] = states
df1['country'] = countries
df1

,pid,Player,info,Position,dob,Shoots,height,height_cm,weight,city,state,country
0,aaltoan01,Antti Aalto,"['Position: C\xa0•\xa0 Shoots: Left\n', '6-...",C,1975-03-04,Left,6-1,185,210,Lappeenranta,Finland,fi
1,aaltoju01,Juhamatti Aaltonen,"['Position: RW\n', ' Born: June 4,\xa01985 ...",RW,1985-06-04,,,,,,,
2,aaltole01,Leevi Aaltonen,"['Position: RW\xa0•\xa0 Shoots: Left\n', '5...",RW,2001-01-24,Left,5-8,173,177,Mikkeli,Finland,fi
3,aaltomi01,Miro Aaltonen,"['Position: C\xa0•\xa0 Shoots: Left\n', '6-...",C,1993-06-07,Left,6-0,183,176,Joensuu,Finland,fi
4,abbeybr01,Bruce Abbey,"['Position: D\xa0•\xa0 Shoots: Left\n', '6-...",D,1951-08-18,Left,6-1,185,185,Toronto,Ontario,ca
...,...,...,...,...,...,...,...,...,...,...,...,...
11360,zukwa01,Wayne Zuk,"['Position: C\xa0•\xa0 Shoots: Right\n', '5...",C,1949-10-29,Right,5-8,173,160,,,
11361,zukemi01,Mike Zuke,"['Position: C\xa0•\xa0 Shoots: Right\n', '6...",C,1954-04-16,Right,6-0,183,180,,,
11362,zunicru01,Rudy Zunich,"['Position: D\xa0•\xa0 Shoots: Left\n', '5-...",D,1910-11-24,Left,5-9,175,170,Calumet,Michigan,us
11363,zykovva01,Valentin Zykov,"['Position: LW\xa0•\xa0 Shoots: Right\n', '...",LW,1995-05-15,Right,6-0,183,200,,,
11364,zyuzian01,Andrei Zyuzin,"['Position: D\xa0•\xa0 Shoots: Left\n', '6-...",D,1978-01-21,Left,6-1,185,208,Ufa,USSR,su

In [394]:
df1['country'].value_counts()

      4483
ca    4354
us    1031
se     488
fi     319
cs     237
su     236
de      47
ch      41
dk      20
sk      13
lv      11
by      11
at      10
no      10
fr       8
pl       6
it       4
ie       4
si       3
yu       3
br       2
be       2
ve       2
jm       2
jp       2
ng       2
au       2
nl       2
py       1
lt       1
bs       1
uz       1
tw       1
cn       1
ua       1
bg       1
id       1
lb       1
Name: country, dtype: int64

In [411]:
pd.read_html('https://www.nationsonline.org/oneworld/country_code_list.html')

HTTPError: HTTP Error 403: Forbidden